-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local ZoneArc = {
    Base   = require('drift-mode.models.Elements.Scorables.ZoneArc.Drawers.ZoneArc.Base'),
    Setup  = require('drift-mode.models.Elements.Scorables.ZoneArc.Drawers.ZoneArc.Setup'),
    Simple = require('drift-mode.models.Elements.Scorables.ZoneArc.Drawers.ZoneArc.Simple'),
}

return ZoneArc
