-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    Base           = require('drift-mode.models.Common.Point.Drawers.Base'),
    BaseGroup      = require('drift-mode.models.Common.Point.Drawers.BaseGroup'),
    GroupConnected = require('drift-mode.models.Common.Point.Drawers.GroupConnected'),
    GroupSimple    = require('drift-mode.models.Common.Point.Drawers.GroupSimple'),
    Simple         = require('drift-mode.models.Common.Point.Drawers.Simple'),
    Sphere         = require('drift-mode.models.Common.Point.Drawers.Sphere'),
}

return Drawers
