-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    State   = require('drift-mode.models.Elements.Scorables.ZoneArc.Drawers.State.init'),
    ZoneArc = require('drift-mode.models.Elements.Scorables.ZoneArc.Drawers.ZoneArc.init'),
}

return Drawers
