-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Clip = {
    Clip      = require('drift-mode.models.TrackObjects.ScoringObject.Clip.Clip'),
    ClipState = require('drift-mode.models.TrackObjects.ScoringObject.Clip.ClipState'),
}

return Clip
