-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Common = {
    Arc     = require('drift-mode.models.Common.Arc'),
    Array   = require('drift-mode.models.Common.Array'),
    Box2D   = require('drift-mode.models.Common.Box2D'),
    Circle  = require('drift-mode.models.Common.Circle'),
    Point   = require('drift-mode.models.Common.Point.init'),
    Segment = require('drift-mode.models.Common.Segment.init'),
}

return Common
