#!/bin/bash

MODEL_FILE='lua_libs/drift-mode/models.lua'
MODELS_DIR='lua_libs/drift-mode/models'
MODELS="$(ls $MODELS_DIR | cut -d'.' -f1)"

echo "-- This file is autogenerated by $0" > ${MODEL_FILE}
echo "-- Do not edit manually" >> ${MODEL_FILE}
echo "" >> ${MODEL_FILE}
echo "-- Load models to global namespace" >> ${MODEL_FILE}
echo "" >> ${MODEL_FILE}

for M in $MODELS; do
    printf "%-20s = require('drift-mode/models/%s')\n" "$M" "$M" >> ${MODEL_FILE}
done