#!/usr/bin/env python

import os

MODELS_FILE = "lua_libs/drift-mode/models.lua"
MODELS_DIR = "lua_libs/drift-mode/models"


class LuaTableWriter:

    def __init__(self):
        self.file_path: str = MODELS_FILE
        self.current_depth = 0
        self.indent_size = 4
        self.comma_needed = False

    def open(self):
        from pathlib import Path

        self.file = open(self.file_path, "w")
        self.file.write(f"-- This file is autogenerated by {Path(__file__).name}\n")
        self.file.write("-- Do not edit manually\n")
        self.file.write("\n")
        self.file.write("-- Load models to global namespace\n")
        self.file.write("\n")

    def close(self):
        self.file.close()

    def startTable(self, symbol):
        if self.current_depth > 0 and self.comma_needed:
            self.file.write(",")
        self.file.write("\n")
        self.file.write(" " * self.indent_size * self.current_depth)
        self.file.write(symbol + " = {")
        self.current_depth += 1
        self.comma_needed = False

    def endTable(self):
        if self.current_depth > 0 and self.comma_needed:
            self.file.write(",")
        self.file.write("\n")
        self.current_depth -= 1
        self.file.write(" " * self.indent_size * self.current_depth)
        self.file.write("}")
        self.comma_needed = True

    def writeRequire(self, symbol, path):
        if self.current_depth > 0 and self.comma_needed:
            self.file.write(",")
        self.file.write("\n")
        self.file.write(" " * self.indent_size * self.current_depth)
        self.file.write(f'{symbol} = require("{path}")')
        self.comma_needed = True


writer = LuaTableWriter()


def visitDir(dir_path):
    print("visiting " + dir_path)

    with os.scandir(dir_path) as dir:
        for obj in dir:
            if obj.is_dir():
                writer.startTable(obj.name)
                visitDir(obj.path)
                writer.endTable()
            if obj.is_file():
                name = obj.name.rsplit(".", 2)[0]  # Strip ext
                path = obj.path.replace("\\", "/")
                path = path.split("/", 1)[1]  # Strip lua_libs/
                path = path.rsplit(".", 2)[0]  # Strip ext
                writer.writeRequire(name, path)


writer.open()
visitDir(MODELS_DIR)
writer.file.write("\n")
writer.close()
