#!/bin/bash

MODELS_FILE='lua_libs/drift-mode/models.lua'
MODELS_DIR='lua_libs/drift-mode/models'
MODELS="$(find ${MODELS_DIR} -type f)"

echo "-- This file is autogenerated by $(basename $0)" > ${MODELS_FILE}
echo "-- Do not edit manually" >> ${MODELS_FILE}
echo "" >> ${MODELS_FILE}
echo "-- Load models to global namespace" >> ${MODELS_FILE}
echo "" >> ${MODELS_FILE}

for MODEL_FILE in $MODELS; do
    MODEL="$(basename ${MODEL_FILE} | cut -d'.' -f1)"
    MODEL_PATH="$(echo ${MODEL_FILE} | sed 's@lua_libs/@@' | cut -d'.' -f1)"
    printf "%-30s = require('%s')\n" "$MODEL" "$MODEL_PATH" >> ${MODELS_FILE}
done
