-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Serializer = {
    CustomSerializerClass = require('drift-mode.models.Tests.Serializer.CustomSerializerClass'),
    MainClass             = require('drift-mode.models.Tests.Serializer.MainClass'),
    ModeFieldsOnly        = require('drift-mode.models.Tests.Serializer.ModeFieldsOnly'),
    NestedClass           = require('drift-mode.models.Tests.Serializer.NestedClass'),
}

return Serializer
