-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local POIs = {
    ObjectEditorPoi  = require('drift-mode.models.CourseEditorUtils.POIs.ObjectEditorPoi'),
    PoiClip          = require('drift-mode.models.CourseEditorUtils.POIs.PoiClip'),
    PoiSegment       = require('drift-mode.models.CourseEditorUtils.POIs.PoiSegment'),
    PoiStartingPoint = require('drift-mode.models.CourseEditorUtils.POIs.PoiStartingPoint'),
    PoiZone          = require('drift-mode.models.CourseEditorUtils.POIs.PoiZone'),
}

return POIs
