-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local POIs = {
    Base    = require('drift-mode.models.Editor.POIs.Base'),
    Drawers = require('drift-mode.models.Editor.POIs.Drawers.init'),
    Segment = require('drift-mode.models.Editor.POIs.Segment'),
}

return POIs
