-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    Base   = require('drift-mode.models.Elements.Gate.Drawers.Base'),
    Setup  = require('drift-mode.models.Elements.Gate.Drawers.Setup'),
    Simple = require('drift-mode.models.Elements.Gate.Drawers.Simple'),
}

return Drawers
