-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Position = {
    StartingPoint = require('drift-mode.models.Elements.Position.StartingPoint'),
}

return Position
