-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Course = {
    RunState        = require('drift-mode.models.TrackObjects.Course.RunState'),
    TrackConfig     = require('drift-mode.models.TrackObjects.Course.TrackConfig'),
    TrackConfigInfo = require('drift-mode.models.TrackObjects.Course.TrackConfigInfo'),
}

return Course
