-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Elements = {
    Course    = require('drift-mode.models.Elements.Course'),
    Gate      = require('drift-mode.models.Elements.Gate'),
    Position  = require('drift-mode.models.Elements.Position'),
    Scorables = require('drift-mode.models.Elements.Scorables'),
}

return Elements
