-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local TrackObjects = {
    Course        = require('drift-mode.models.TrackObjects.Course'),
    Gate          = require('drift-mode.models.TrackObjects.Gate'),
    Position      = require('drift-mode.models.TrackObjects.Position'),
    ScoringObject = require('drift-mode.models.TrackObjects.ScoringObject'),
}

return TrackObjects
