-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Arc = {
    Arc     = require('drift-mode.models.Common.Arc.Arc'),
    Drawers = require('drift-mode.models.Common.Arc.Drawers.init'),
}

return Arc
