-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    DrawerCourse       = require('drift-mode.models.Elements.Course.Drawers.DrawerCourse'),
    DrawerCoursePlay   = require('drift-mode.models.Elements.Course.Drawers.DrawerCoursePlay'),
    DrawerCourseSetup  = require('drift-mode.models.Elements.Course.Drawers.DrawerCourseSetup'),
    DrawerRunState     = require('drift-mode.models.Elements.Course.Drawers.DrawerRunState'),
    DrawerRunStatePlay = require('drift-mode.models.Elements.Course.Drawers.DrawerRunStatePlay'),
}

return Drawers
