-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local CourseEditorUtils = {
  POIs = require("drift-mode/models/CourseEditorUtils/POIs"),
  Routines = require("drift-mode/models/CourseEditorUtils/Routines"),
}
return CourseEditorUtils
