-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
  Drawer = require("drift-mode/models/Drawers/Drawer"),
  DrawerClip = require("drift-mode/models/Drawers/DrawerClip"),
  DrawerClipPlay = require("drift-mode/models/Drawers/DrawerClipPlay"),
  DrawerClipSetup = require("drift-mode/models/Drawers/DrawerClipSetup"),
  DrawerClipState = require("drift-mode/models/Drawers/DrawerClipState"),
  DrawerClipStatePlay = require("drift-mode/models/Drawers/DrawerClipStatePlay"),
  DrawerCourse = require("drift-mode/models/Drawers/DrawerCourse"),
  DrawerCoursePlay = require("drift-mode/models/Drawers/DrawerCoursePlay"),
  DrawerCourseSetup = require("drift-mode/models/Drawers/DrawerCourseSetup"),
  DrawerObjectEditorPoi = require("drift-mode/models/Drawers/DrawerObjectEditorPoi"),
  DrawerPoint = require("drift-mode/models/Drawers/DrawerPoint"),
  DrawerPointGroup = require("drift-mode/models/Drawers/DrawerPointGroup"),
  DrawerPointGroupConnected = require("drift-mode/models/Drawers/DrawerPointGroupConnected"),
  DrawerPointGroupSimple = require("drift-mode/models/Drawers/DrawerPointGroupSimple"),
  DrawerPointSimple = require("drift-mode/models/Drawers/DrawerPointSimple"),
  DrawerPointSphere = require("drift-mode/models/Drawers/DrawerPointSphere"),
  DrawerRunState = require("drift-mode/models/Drawers/DrawerRunState"),
  DrawerRunStatePlay = require("drift-mode/models/Drawers/DrawerRunStatePlay"),
  DrawerSegment = require("drift-mode/models/Drawers/DrawerSegment"),
  DrawerSegmentLine = require("drift-mode/models/Drawers/DrawerSegmentLine"),
  DrawerSegmentWall = require("drift-mode/models/Drawers/DrawerSegmentWall"),
  DrawerStartingPoint = require("drift-mode/models/Drawers/DrawerStartingPoint"),
  DrawerStartingPointSetup = require("drift-mode/models/Drawers/DrawerStartingPointSetup"),
  DrawerZone = require("drift-mode/models/Drawers/DrawerZone"),
  DrawerZonePlay = require("drift-mode/models/Drawers/DrawerZonePlay"),
  DrawerZoneSetup = require("drift-mode/models/Drawers/DrawerZoneSetup"),
  DrawerZoneState = require("drift-mode/models/Drawers/DrawerZoneState"),
  DrawerZoneStatePlay = require("drift-mode/models/Drawers/DrawerZoneStatePlay"),
}
return Drawers
