-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local models = {
    Common    = require('drift-mode.models.Common'),
    Drawer    = require('drift-mode.models.Drawer'),
    Drawers   = require('drift-mode.models.Drawers'),
    Editor    = require('drift-mode.models.Editor'),
    Elements  = require('drift-mode.models.Elements'),
    Misc      = require('drift-mode.models.Misc'),
    ModelBase = require('drift-mode.models.ModelBase'),
    Range     = require('drift-mode.models.Range'),
    Tests     = require('drift-mode.models.Tests'),
}

return models
