-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local models = {
    Clip               = require('drift-mode.models.Clip'),
    ClipState          = require('drift-mode.models.ClipState'),
    Common             = require('drift-mode.models.Common'),
    CourseEditorUtils  = require('drift-mode.models.CourseEditorUtils'),
    Cursor             = require('drift-mode.models.Cursor'),
    CursorObject       = require('drift-mode.models.CursorObject'),
    Drawers            = require('drift-mode.models.Drawers'),
    Editor             = require('drift-mode.models.Editor'),
    EditorsState       = require('drift-mode.models.EditorsState'),
    Misc               = require('drift-mode.models.Misc'),
    ModelBase          = require('drift-mode.models.ModelBase'),
    Range              = require('drift-mode.models.Range'),
    RunState           = require('drift-mode.models.RunState'),
    ScoringObject      = require('drift-mode.models.ScoringObject'),
    ScoringObjectState = require('drift-mode.models.ScoringObjectState'),
    ScoringRanges      = require('drift-mode.models.ScoringRanges'),
    StartingPoint      = require('drift-mode.models.StartingPoint'),
    Tests              = require('drift-mode.models.Tests'),
    TrackConfig        = require('drift-mode.models.TrackConfig'),
    TrackConfigInfo    = require('drift-mode.models.TrackConfigInfo'),
    Zone               = require('drift-mode.models.Zone'),
    ZoneScoringPoint   = require('drift-mode.models.ZoneScoringPoint'),
    ZoneState          = require('drift-mode.models.ZoneState'),
}

return models
