-- Load models to global namespace

Point = require('drift-mode/models/Point')
PointGroup = require('drift-mode/models/PointGroup')
Segment = require('drift-mode/models/Segment')
SegmentGroup = require('drift-mode/models/SegmentGroup')
Zone = require('drift-mode/models/Zone')
ClippingPoint = require('drift-mode/models/ClippingPoint')
TrackConfig = require('drift-mode/models/TrackConfig')
CarConfig = require('drift-mode/models/CarConfig')
Cursor = require('drift-mode/models/Cursor')
GameState = require('drift-mode/models/GameState')
RunState = require('drift-mode/models/RunState')
ZoneState = require('drift-mode/models/ZoneState')
ZoneScoringPoint = require('drift-mode/models/ZoneScoringPoint')
ZoneStateData = require('drift-mode/models/ZoneStateData')
RunStateData = require('drift-mode/models/RunStateData')
StartingPoint = require('drift-mode/models/StartingPoint')
DriftState = require('drift-mode/models/DriftState')
