-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

-- Load models to global namespace


Box2D = require("drift-mode/models/Box2D")
CarConfig = require("drift-mode/models/CarConfig")
Clip = require("drift-mode/models/Clip")
ClipState = require("drift-mode/models/ClipState")
CourseEditorUtils = {
    POIs = {
        ObjectEditorPoi = require("drift-mode/models/CourseEditorUtils/POIs/ObjectEditorPoi"),
        PoiClip = require("drift-mode/models/CourseEditorUtils/POIs/PoiClip"),
        PoiSegment = require("drift-mode/models/CourseEditorUtils/POIs/PoiSegment"),
        PoiStartingPoint = require("drift-mode/models/CourseEditorUtils/POIs/PoiStartingPoint"),
        PoiZone = require("drift-mode/models/CourseEditorUtils/POIs/PoiZone")
    },
    Routines = {
        EditorRoutine = require("drift-mode/models/CourseEditorUtils/Routines/EditorRoutine"),
        RoutineExtendPointGroup = require("drift-mode/models/CourseEditorUtils/Routines/RoutineExtendPointGroup"),
        RoutineMovePoi = require("drift-mode/models/CourseEditorUtils/Routines/RoutineMovePoi"),
        RoutineSelectSegment = require("drift-mode/models/CourseEditorUtils/Routines/RoutineSelectSegment")
    }
}
Cursor = require("drift-mode/models/Cursor")
CursorObject = require("drift-mode/models/CursorObject")
Drawers = {
    Drawer = require("drift-mode/models/Drawers/Drawer"),
    DrawerClip = require("drift-mode/models/Drawers/DrawerClip"),
    DrawerClipPlay = require("drift-mode/models/Drawers/DrawerClipPlay"),
    DrawerClipSetup = require("drift-mode/models/Drawers/DrawerClipSetup"),
    DrawerClipState = require("drift-mode/models/Drawers/DrawerClipState"),
    DrawerClipStatePlay = require("drift-mode/models/Drawers/DrawerClipStatePlay"),
    DrawerCourse = require("drift-mode/models/Drawers/DrawerCourse"),
    DrawerCoursePlay = require("drift-mode/models/Drawers/DrawerCoursePlay"),
    DrawerCourseSetup = require("drift-mode/models/Drawers/DrawerCourseSetup"),
    DrawerObjectEditorPoi = require("drift-mode/models/Drawers/DrawerObjectEditorPoi"),
    DrawerPoint = require("drift-mode/models/Drawers/DrawerPoint"),
    DrawerPointGroup = require("drift-mode/models/Drawers/DrawerPointGroup"),
    DrawerPointGroupConnected = require("drift-mode/models/Drawers/DrawerPointGroupConnected"),
    DrawerPointGroupSimple = require("drift-mode/models/Drawers/DrawerPointGroupSimple"),
    DrawerPointSimple = require("drift-mode/models/Drawers/DrawerPointSimple"),
    DrawerPointSphere = require("drift-mode/models/Drawers/DrawerPointSphere"),
    DrawerRunState = require("drift-mode/models/Drawers/DrawerRunState"),
    DrawerRunStatePlay = require("drift-mode/models/Drawers/DrawerRunStatePlay"),
    DrawerSegment = require("drift-mode/models/Drawers/DrawerSegment"),
    DrawerSegmentLine = require("drift-mode/models/Drawers/DrawerSegmentLine"),
    DrawerSegmentWall = require("drift-mode/models/Drawers/DrawerSegmentWall"),
    DrawerStartingPoint = require("drift-mode/models/Drawers/DrawerStartingPoint"),
    DrawerStartingPointSetup = require("drift-mode/models/Drawers/DrawerStartingPointSetup"),
    DrawerZone = require("drift-mode/models/Drawers/DrawerZone"),
    DrawerZonePlay = require("drift-mode/models/Drawers/DrawerZonePlay"),
    DrawerZoneSetup = require("drift-mode/models/Drawers/DrawerZoneSetup"),
    DrawerZoneState = require("drift-mode/models/Drawers/DrawerZoneState"),
    DrawerZoneStatePlay = require("drift-mode/models/Drawers/DrawerZoneStatePlay")
}
DriftState = require("drift-mode/models/DriftState")
EditorsState = require("drift-mode/models/EditorsState")
Point = require("drift-mode/models/Point")
PointGroup = require("drift-mode/models/PointGroup")
Range = require("drift-mode/models/Range")
RunState = require("drift-mode/models/RunState")
ScoringObject = require("drift-mode/models/ScoringObject")
ScoringObjectState = require("drift-mode/models/ScoringObjectState")
ScoringRanges = require("drift-mode/models/ScoringRanges")
Segment = require("drift-mode/models/Segment")
SegmentGroup = require("drift-mode/models/SegmentGroup")
StartingPoint = require("drift-mode/models/StartingPoint")
TrackConfig = require("drift-mode/models/TrackConfig")
TrackConfigInfo = require("drift-mode/models/TrackConfigInfo")
WorldObject = require("drift-mode/models/WorldObject")
Zone = require("drift-mode/models/Zone")
ZoneScoringPoint = require("drift-mode/models/ZoneScoringPoint")
ZoneState = require("drift-mode/models/ZoneState")
