-- This file is autogenerated by ./generate_models.sh
-- Do not edit manually

-- Load models to global namespace

CarConfig            = require('drift-mode/models/CarConfig')
Clip                 = require('drift-mode/models/Clip')
ClipState            = require('drift-mode/models/ClipState')
ClipStateData        = require('drift-mode/models/ClipStateData')
Cursor               = require('drift-mode/models/Cursor')
DriftState           = require('drift-mode/models/DriftState')
GameState            = require('drift-mode/models/GameState')
Point                = require('drift-mode/models/Point')
PointGroup           = require('drift-mode/models/PointGroup')
Range                = require('drift-mode/models/Range')
RunState             = require('drift-mode/models/RunState')
RunStateData         = require('drift-mode/models/RunStateData')
ScoringRanges        = require('drift-mode/models/ScoringRanges')
Segment              = require('drift-mode/models/Segment')
SegmentGroup         = require('drift-mode/models/SegmentGroup')
StartingPoint        = require('drift-mode/models/StartingPoint')
StartLine            = require('drift-mode/models/StartLine')
TrackConfig          = require('drift-mode/models/TrackConfig')
TrackConfigInfo      = require('drift-mode/models/TrackConfigInfo')
Zone                 = require('drift-mode/models/Zone')
ZoneScoringPoint     = require('drift-mode/models/ZoneScoringPoint')
ZoneState            = require('drift-mode/models/ZoneState')
ZoneStateData        = require('drift-mode/models/ZoneStateData')
