-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    State = require('drift-mode.models.Elements.Scorables.Zone.Drawers.State.init'),
    Zone  = require('drift-mode.models.Elements.Scorables.Zone.Drawers.Zone.init'),
}

return Drawers
