-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Routines = {
    EditorRoutine           = require('drift-mode.models.Editor.Routines.EditorRoutine'),
    RoutineExtendPointArray = require('drift-mode.models.Editor.Routines.RoutineExtendPointArray'),
    RoutineMovePoi          = require('drift-mode.models.Editor.Routines.RoutineMovePoi'),
    RoutineSelectSegment    = require('drift-mode.models.Editor.Routines.RoutineSelectSegment'),
    SelectArc               = require('drift-mode.models.Editor.Routines.SelectArc'),
}

return Routines
