-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Routines = {
    EditorRoutine           = require('drift-mode.models.Editor.Routines.EditorRoutine'),
    RoutineExtendPointGroup = require('drift-mode.models.Editor.Routines.RoutineExtendPointGroup'),
    RoutineMovePoi          = require('drift-mode.models.Editor.Routines.RoutineMovePoi'),
    RoutineSelectSegment    = require('drift-mode.models.Editor.Routines.RoutineSelectSegment'),
}

return Routines
