-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Segment = {
    Array   = require('drift-mode.models.Common.Segment.Array'),
    Drawers = require('drift-mode.models.Common.Segment.Drawers.init'),
    Segment = require('drift-mode.models.Common.Segment.Segment'),
}

return Segment
