-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Misc = {
    CarConfig  = require('drift-mode.models.Misc.CarConfig'),
    DriftState = require('drift-mode.models.Misc.DriftState'),
}

return Misc
