-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local HandleManager = {
    Manager = require('drift-mode.models.Editor.HandleManager.Manager'),
    Reader  = require('drift-mode.models.Editor.HandleManager.Reader'),
    Setter  = require('drift-mode.models.Editor.HandleManager.Setter'),
}

return HandleManager
