-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    DrawerObjectEditorPoi = require('drift-mode.models.Drawers.DrawerObjectEditorPoi'),
}

return Drawers
