-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    ArrayConnected = require('drift-mode.models.Common.Point.Drawers.ArrayConnected'),
    ArraySimple    = require('drift-mode.models.Common.Point.Drawers.ArraySimple'),
    Base           = require('drift-mode.models.Common.Point.Drawers.Base'),
    BaseArray      = require('drift-mode.models.Common.Point.Drawers.BaseArray'),
    Precise        = require('drift-mode.models.Common.Point.Drawers.Precise'),
    Simple         = require('drift-mode.models.Common.Point.Drawers.Simple'),
    Sphere         = require('drift-mode.models.Common.Point.Drawers.Sphere'),
}

return Drawers
