-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Zone = {
    Base   = require('drift-mode.models.Elements.Scorables.Zone.Drawers.Zone.Base'),
    Setup  = require('drift-mode.models.Elements.Scorables.Zone.Drawers.Zone.Setup'),
    Simple = require('drift-mode.models.Elements.Scorables.Zone.Drawers.Zone.Simple'),
}

return Zone
