-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    Base = require('drift-mode.models.Common.Segment.Drawers.Base'),
    Line = require('drift-mode.models.Common.Segment.Drawers.Line'),
    Wall = require('drift-mode.models.Common.Segment.Drawers.Wall'),
}

return Drawers
