-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local ScoringObject = {
    Clip = require('drift-mode.models.TrackObjects.ScoringObject.Clip'),
    Zone = require('drift-mode.models.TrackObjects.ScoringObject.Zone'),
}

return ScoringObject
