-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    Base   = require('drift-mode.models.Common.Arc.Drawers.Base'),
    Debug  = require('drift-mode.models.Common.Arc.Drawers.Debug'),
    Setup  = require('drift-mode.models.Common.Arc.Drawers.Setup'),
    Simple = require('drift-mode.models.Common.Arc.Drawers.Simple'),
}

return Drawers
