-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Segment = {
    Drawers      = require('drift-mode.models.Common.Segment.Drawers.init'),
    Segment      = require('drift-mode.models.Common.Segment.Segment'),
    SegmentGroup = require('drift-mode.models.Common.Segment.SegmentGroup'),
}

return Segment
