-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Clip = {
    Base   = require('drift-mode.models.Elements.Scorables.Clip.Drawers.Clip.Base'),
    Setup  = require('drift-mode.models.Elements.Scorables.Clip.Drawers.Clip.Setup'),
    Simple = require('drift-mode.models.Elements.Scorables.Clip.Drawers.Clip.Simple'),
}

return Clip
