-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local State = {
    Base   = require('drift-mode.models.Elements.Scorables.Zone.Drawers.State.Base'),
    Simple = require('drift-mode.models.Elements.Scorables.Zone.Drawers.State.Simple'),
}

return State
