-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Elements = {
    Course    = require('drift-mode.models.Elements.Course.init'),
    Element   = require('drift-mode.models.Elements.Element'),
    Gate      = require('drift-mode.models.Elements.Gate.init'),
    Handle    = require('drift-mode.models.Elements.Handle'),
    Position  = require('drift-mode.models.Elements.Position.init'),
    Scorables = require('drift-mode.models.Elements.Scorables.init'),
}

return Elements
