-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Point = {
    Drawers    = require('drift-mode.models.Common.Point.Drawers.init'),
    Point      = require('drift-mode.models.Common.Point.Point'),
    PointGroup = require('drift-mode.models.Common.Point.PointGroup'),
}

return Point
