-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Point = {
    Array   = require('drift-mode.models.Common.Point.Array'),
    Drawers = require('drift-mode.models.Common.Point.Drawers.init'),
    Point   = require('drift-mode.models.Common.Point.Point'),
}

return Point
