-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    DrawerStartingPoint      = require('drift-mode.models.Elements.Position.Drawers.DrawerStartingPoint'),
    DrawerStartingPointSetup = require('drift-mode.models.Elements.Position.Drawers.DrawerStartingPointSetup'),
}

return Drawers
