-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    Base  = require('drift-mode.models.Elements.Position.Drawers.Base'),
    Setup = require('drift-mode.models.Elements.Position.Drawers.Setup'),
}

return Drawers
