-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Scorables = {
    Clip               = require('drift-mode.models.Elements.Scorables.Clip'),
    ScoringObject      = require('drift-mode.models.Elements.Scorables.ScoringObject'),
    ScoringObjectState = require('drift-mode.models.Elements.Scorables.ScoringObjectState'),
    ScoringRanges      = require('drift-mode.models.Elements.Scorables.ScoringRanges'),
    Zone               = require('drift-mode.models.Elements.Scorables.Zone'),
}

return Scorables
