-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Scorables = {
    Clip          = require('drift-mode.models.Elements.Scorables.Clip.init'),
    Scorable      = require('drift-mode.models.Elements.Scorables.Scorable'),
    ScorableState = require('drift-mode.models.Elements.Scorables.ScorableState'),
    ScoringRanges = require('drift-mode.models.Elements.Scorables.ScoringRanges'),
    Zone          = require('drift-mode.models.Elements.Scorables.Zone.init'),
    ZoneArc       = require('drift-mode.models.Elements.Scorables.ZoneArc.init'),
}

return Scorables
