-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local ZoneArc = {
    Drawers             = require('drift-mode.models.Elements.Scorables.ZoneArc.Drawers.init'),
    ZoneArc             = require('drift-mode.models.Elements.Scorables.ZoneArc.ZoneArc'),
    ZoneArcScoringPoint = require('drift-mode.models.Elements.Scorables.ZoneArc.ZoneArcScoringPoint'),
    ZoneArcState        = require('drift-mode.models.Elements.Scorables.ZoneArc.ZoneArcState'),
}

return ZoneArc
