-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Zone = {
    Zone             = require('drift-mode.models.Elements.Scorables.Zone.Zone'),
    ZoneScoringPoint = require('drift-mode.models.Elements.Scorables.Zone.ZoneScoringPoint'),
    ZoneState        = require('drift-mode.models.Elements.Scorables.Zone.ZoneState'),
}

return Zone
