-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Drawers = {
    Clip  = require('drift-mode.models.Elements.Scorables.Clip.Drawers.Clip.init'),
    State = require('drift-mode.models.Elements.Scorables.Clip.Drawers.State.init'),
}

return Drawers
