-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Routines = {
  EditorRoutine = require("drift-mode/models/CourseEditorUtils/Routines/EditorRoutine"),
  RoutineExtendPointGroup = require("drift-mode/models/CourseEditorUtils/Routines/RoutineExtendPointGroup"),
  RoutineMovePoi = require("drift-mode/models/CourseEditorUtils/Routines/RoutineMovePoi"),
  RoutineSelectSegment = require("drift-mode/models/CourseEditorUtils/Routines/RoutineSelectSegment"),
}
return Routines
