-- This file is autogenerated by generate_models_tree.py
-- Do not edit manually

local Position = {
    Drawers  = require('drift-mode.models.Elements.Position.Drawers.init'),
    Handle   = require('drift-mode.models.Elements.Position.Handle'),
    Position = require('drift-mode.models.Elements.Position.Position'),
}

return Position
